name: Build
on:
  - push
  - workflow_dispatch

# Prevent concurrent builds of the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-configs:
    runs-on: ubuntu-latest
    steps:
      # Free additional disk space for build
      - name: Free disk space
        uses: thiagokokada/free-disk-space@main
        with:
          opt: true
          tool-cache: true
          usrlocal: true
          usrmisc: true

      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |-
            accept-flake-config = true
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v15
        with:
          name: gabehoban
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: nix-community, chaotic-nyx

      - name: "Build NixOS configs for: workstation and sekio"
        run: |-
          nix build --print-build-logs '.#nixosConfigurations.workstation.config.system.build.toplevel'
          nix build --print-build-logs '.#nixosConfigurations.sekio.config.system.build.toplevel'
