name: Build
on:
  - push
  - workflow_dispatch

jobs:
  build:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      # Here we specify the matrix of our hosts and their target platform architectures
      matrix:
        machine:
          - host: workstation
            platform: x86-64-linux
          - host: nuc-luna
            platform: x86-64-linux
          - host: nuc-titan
            platform: x86-64-linux
          - host: nuc-juno
            platform: x86-64-linux
          - host: rpi-casio
            platform: aarch64-linux
          - host: rpi-sekio
            platform: aarch64-linux

    steps:
      - uses: actions/checkout@v4

      - if: matrix.machine.platform == 'aarch64-linux'
        uses: docker/setup-qemu-action@v3

      - name: Build and push system
        run: |
          nix build --accept-flake-config .#nixosConfigurations.${{ matrix.machine.host }}.config.system.build.toplevel
          nix run github:zhaofengli/attic#default login labrats https://cache.labrats.cc ${{ secrets.ATTIC_TOKEN }}
          nix run github:zhaofengli/attic#default push system result -j 2
