name: build-nixos-hosts
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  push:
    paths-ignore:
      - "**/*.md"
      - ".github/**"
      - "_img/**"
  workflow_dispatch:
jobs:
  build-workstation:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
      - uses: actions/checkout@main
        with:
          fetch-depth: 1
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@master
        with:
          name: gabehoban
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build workstation
        run: nix build --accept-flake-config .#nixosConfigurations.workstation.config.system.build.toplevel
