name: update-flakes
on:
  schedule:
    - cron: "0 0 */3 * *"
  workflow_dispatch:

permissions: {}

jobs:
  get-flake-inputs:
    runs-on: ubuntu-latest
    outputs:
      flake-inputs: ${{ steps.get-flake-inputs.outputs.flake-inputs }}
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: flake.lock
      - id: get-flake-inputs
        run: |
          flake_inputs="$(jq -c '.nodes.root.inputs | {flake: keys}' flake.lock)"
          echo "flake-inputs=${flake_inputs}" >> "$GITHUB_OUTPUT"
  update-flake:
    name: update-${{ matrix.flake }}
    runs-on: ubuntu-latest
    needs: get-flake-inputs
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.get-flake-inputs.outputs.flake-inputs) }}
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"
      - uses: actions/checkout@v4
        with:
          lfs: false
      - uses: DeterminateSystems/nix-installer-action@v16
        with:
          extra-conf: accept-flake-config = true
      - run: git config --global user.email "45900957864+dev-baymax[bot]@users.noreply.github.com"
      - run: git config --global user.name "dev-baymax[bot]"
      - uses: cpcloud/flake-update-action@v2.0.1
        with:
          dependency: ${{ matrix.flake }}
          pull-request-token: "${{ steps.app-token.outputs.token }}"
          pull-request-author: dev-baymax[bot] <45900957864+dev-baymax[bot]@users.noreply.github.com>
          delete-branch: true
          github-token: "${{ steps.app-token.outputs.token }}"
          pull-request-branch-prefix: update-
          automerge: true
