---
name: Cache 📝

"on":
  push:
    branches:
      - main
      - cache

    paths:
      - "**.nix"
      - "**.age"
      - "flake.lock"

concurrency:
  group: ci-${{ github.ref }}-cache
  cancel-in-progress: true

jobs:
  cache:
    name: Cache 📝
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        hostname:
          - workstation

    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v16
      - uses: cachix/cachix-action@v16
        with:
          name: gabehoban
          extraPullNames: "nix-community"
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      # Build systems.
      - name: Build system derivation
        run: "nix build .#nixosConfigurations.${{ matrix.hostname }}.config.system.build.toplevel"
