name: Update
on:
  schedule:
    - cron: 0 2 * * *
  workflow_dispatch: null

# Prevent concurrent runs
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  update-flakes:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"
      - uses: thiagokokada/free-disk-space@main
        with:
          opt: true
          tool-cache: true
          usrlocal: true
          usrmisc: true
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |-
            accept-flake-config = true
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v15
        with:
          name: gabehoban
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: nix-community, chaotic-nyx
      - name: Update flake.lock
        run: |
          git config user.name "dev-baymax[bot]"
          git config user.email "dev-baymax[bot]@users.noreply.github.com"
          nix flake update --commit-lock-file
      - name: "Build NixOS configs for: workstation"
        run: |-
          nix build --print-build-logs '.#nixosConfigurations.workstation.config.system.build.toplevel'
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        id: create_pr
        with:
          token: "${{ steps.app-token.outputs.token }}"
          body: |
            ## Run report

            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          branch: flake-updates
          delete-branch: true
          title: "chore: update flake.lock file"
      - name: Merge Pull Request
        run: gh pr merge ${{ steps.create_pr.outputs.pull-request-number }} --auto --squash --delete-branch
        env:
          GITHUB_TOKEN: "${{ steps.app-token.outputs.token }}"
