name: Update
on:
  schedule:
    - cron: 0 2 * * *
  workflow_dispatch: null

# Prevent concurrent runs
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        id: update
        with:
          commit-msg: "chore: update flake.lock file"
          pr-title: "chore: update flake.lock file"
          pr-body: |
            Automated changes by the [update-flake-lock](https://github.com/DeterminateSystems/update-flake-lock) GitHub Action.

            ```
            {{ env.GIT_COMMIT_MESSAGE }}
            ```

          git-author-name: "dev-baymax[bot]"
          git-author-email: "dev-baymax[bot]@users.noreply.github.com"
          git-committer-name: "dev-baymax[bot]"
          git-committer-email: "dev-baymax[bot]@users.noreply.github.com"
          token: "${{ steps.app-token.outputs.token }}"
      - name: Merge pull request
        run: gh pr merge ${{ steps.update.outputs.pull-request-number }} --auto --squash --delete-branch
        env:
          GITHUB_TOKEN: "${{ steps.app-token.outputs.token }}"
